STRUCTURE = {
  addresses: {
    id: {
      oid: 23,
      comment: nil,
      db_type: "integer",
      default: nil,
      allow_null: false,
      primary_key: true,
      generated: false,
      type: "integer",
      auto_increment: true,
      ruby_default: nil,
      min_value: -2147483648,
      max_value: 2147483647
    },
    city: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: false,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    country: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: false,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    postal: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: false,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    region: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    street_line1: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: false,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    street_line2: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    lt: {
      oid: 701,
      comment: nil,
      db_type: "double precision",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "float",
      ruby_default: nil
    },
    ln: {
      oid: 701,
      comment: nil,
      db_type: "double precision",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "float",
      ruby_default: nil
    },
    created: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    },
    updated: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    }
  },
  images: {
    id: {
      oid: 23,
      comment: nil,
      db_type: "integer",
      default: nil,
      allow_null: false,
      primary_key: true,
      generated: false,
      type: "integer",
      auto_increment: true,
      ruby_default: nil,
      min_value: -2147483648,
      max_value: 2147483647
    },
    image_data: {
      oid: 3802,
      comment: nil,
      db_type: "jsonb",
      default: nil,
      allow_null: false,
      primary_key: false,
      generated: false,
      type: nil,
      ruby_default: nil
    },
    created: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    },
    updated: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    }
  },
  companies: {
    id: {
      oid: 23,
      comment: nil,
      db_type: "integer",
      default: nil,
      allow_null: false,
      primary_key: true,
      generated: false,
      type: "integer",
      auto_increment: true,
      ruby_default: nil,
      min_value: -2147483648,
      max_value: 2147483647
    },
    name: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    email: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    website: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    phone: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    description: {
      oid: 25,
      comment: nil,
      db_type: "text",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "string",
      ruby_default: nil
    },
    address_id: {
      oid: 23,
      comment: nil,
      db_type: "integer",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "integer",
      ruby_default: nil,
      min_value: -2147483648,
      max_value: 2147483647
    },
    created: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    },
    updated: {
      oid: 1114,
      comment: nil,
      db_type: "timestamp without time zone",
      default: nil,
      allow_null: true,
      primary_key: false,
      generated: false,
      type: "datetime",
      min_value: "-4713-11-24 00:00:00 UTC",
      max_value: "294276-12-31 23:59:59 UTC",
      ruby_default: nil
    }
  }
}
